import React from 'react';
import { Text, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';

import { Container, InfoList, InfoItem } from './styles';

const data = [
  {
    id: '1',
    title: 'O que é perda auditiva ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '2',
    title: 'Quais os prejuízos do ruído ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '3',
    title: 'O que é reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
    ],
  },
  {
    id: '4',
    title: 'Como combater a reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '5',
    title: 'O que é perda auditiva ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '6',
    title: 'Quais os prejuízos do ruído ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '7',
    title: 'O que é reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '8',
    title: 'Como combater a reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '9',
    title: 'O que é perda auditiva ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '10',
    title: 'Quais os prejuízos do ruído ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '11',
    title: 'O que é reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '12',
    title: 'Como combater a reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '13',
    title: 'O que é perda auditiva ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '14',
    title: 'Quais os prejuízos do ruído ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '15',
    title: 'O que é reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
  {
    id: '16',
    title: 'Como combater a reverberação ?',
    text: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum augue velit, in dapibus nisl ornare sit amet. Sed eu mattis augue, eget venenatis diam. Pellentesque vehicula lacinia libero nec consectetur. Pellentesque lacus dui, porttitor sit amet massa id, rutrum vestibulum justo. Nullam scelerisque est ac tortor maximus, in lacinia neque pellentesque. Aliquam vel neque vitae velit eleifend maximus. Curabitur eu gravida lacus. Sed rhoncus mi nunc, vitae sollicitudin libero ultricies dictum.',
      'Proin malesuada, turpis a maximus bibendum, ex ante pulvinar sapien, vitae eleifend elit tellus placerat nunc. Praesent consequat non elit non feugiat. Pellentesque sollicitudin pretium velit, et tincidunt neque faucibus et. Mauris nec lectus dictum mi porta dictum. Vivamus a nibh non magna vehicula sollicitudin eget id orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor elementum luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a luctus tortor, in tincidunt mauris. Donec eleifend ante ornare sapien aliquam, ac tincidunt odio dictum. Aenean ut facilisis eros. Praesent bibendum nisi vel velit hendrerit, id interdum elit aliquam. Donec nulla lacus, imperdiet ac felis at, eleifend molestie lorem. Vivamus consectetur lacinia nulla, rutrum molestie enim pulvinar vehicula.',
      'Phasellus sit amet ultricies lorem. Nullam bibendum lectus nisl, vel convallis lorem faucibus non. In dapibus, diam sit amet scelerisque ullamcorper, enim nisi tempus massa, nec elementum ex quam sit amet leo. Vivamus finibus nibh quis feugiat posuere. Etiam ultricies elit vel mauris pharetra, at porta massa bibendum. Proin dictum tristique orci. Suspendisse eget sem magna. Etiam vestibulum tellus id odio volutpat, et volutpat ex finibus. Nunc lectus neque, maximus ut odio nec, blandit laoreet mi. Aenean ac rhoncus nisi. Nullam mi risus, blandit nec turpis ut, luctus hendrerit metus.',
      'In ut sodales quam. Sed lobortis erat ut nisl placerat, vitae ultrices neque pharetra. Aliquam erat volutpat. Donec mattis porttitor libero non lobortis. Vivamus non libero erat. Nam sit amet semper lectus. Integer vitae semper turpis. Cras et nulla eget ligula condimentum sollicitudin eget sit amet quam. In sit amet elit enim. Sed lorem lacus, egestas ut pharetra quis, congue vel urna. Mauris commodo orci eu lorem porttitor ultricies. Cras non arcu gravida, ornare metus non, congue est. Praesent ut diam eget lorem tempor auctor at non dolor. Mauris sodales tortor ornare laoreet sodales. Quisque pulvinar diam venenatis vestibulum hendrerit.',
    ],
  },
];

export interface Data {
  id: string;
  title: string;
}

const InfoListScreen: React.FC = () => {
  const { navigate } = useNavigation();

  function handleGoToInfo(index: number) {
    navigate('Info', {
      ...data[index],
    });
  }

  return (
    <Container>
      <InfoList
        data={data}
        renderItem={({ item, index }) => (
          <InfoItem onPress={() => handleGoToInfo(index)}>
            <Text key={item.id}>{item.title}</Text>
          </InfoItem>
        )}
        ItemSeparatorComponent={() => (
          <View
            style={{
              backgroundColor: '#f00',
              height: 1,
            }}
          />
        )}
      />
    </Container>
  );
};

export default InfoListScreen;
